[project]
name = "blackadder-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "datasets>=5.0.0",
    "ipykernel>=7.2.0",
    "liger-kernel>=0.8.0",
    "transformers>=4.57.2",
    "trl>=0.23.0",
    "unsloth>=2025.11.1",
]
